/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej13ComboList;

import javax.swing.DefaultListModel;

/**
 *
 * @author DAM2Alu10
 */
public class JFrameComboSencillo extends javax.swing.JFrame {

    /**
     * Creates new form JFrameComboSencillo
     */
    
    public JFrameComboSencillo() { // Constructor
        initComponents();
        String labels[]= {"A","B","C","D","E","F"};
        jComboBoxLetras.removeAllItems();
        for(String letra: labels){
            jComboBoxLetras.addItem(letra);
        }
        jComboBoxLetras.setMaximumRowCount(4);
        jComboBoxLetras.setSize(300, 30);
        
        DefaultListModel dlm = new DefaultListModel();
        jListSeleccion.setModel(dlm);
        for (int i = 0; i < 10; i++) {
            dlm.addElement(String.valueOf(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxLetras = new javax.swing.JComboBox<>();
        jLabelSelecciona = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSeleccion = new javax.swing.JList<>();
        jButtonRecorreJLIST = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBoxLetras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxLetras.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxLetrasItemStateChanged(evt);
            }
        });
        jComboBoxLetras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboBoxLetrasFocusLost(evt);
            }
        });
        jComboBoxLetras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLetrasActionPerformed(evt);
            }
        });
        jComboBoxLetras.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxLetrasPropertyChange(evt);
            }
        });

        jLabelSelecciona.setText("Selecciona");

        jListSeleccion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListSeleccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListSeleccionMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jListSeleccion);

        jButtonRecorreJLIST.setText("Muestra Seleccion");
        jButtonRecorreJLIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecorreJLISTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelSelecciona)
                                .addGap(47, 47, 47)
                                .addComponent(jComboBoxLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButtonRecorreJLIST)))
                .addContainerGap(402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxLetras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSelecciona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jButtonRecorreJLIST)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLetrasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxLetrasPropertyChange
        
    }//GEN-LAST:event_jComboBoxLetrasPropertyChange

    private void jComboBoxLetrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBoxLetrasFocusLost
        
    }//GEN-LAST:event_jComboBoxLetrasFocusLost

    private void jComboBoxLetrasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxLetrasItemStateChanged
        
    }//GEN-LAST:event_jComboBoxLetrasItemStateChanged

    private void jComboBoxLetrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLetrasActionPerformed
        System.out.println("Letra seleccionada: " + (String)jComboBoxLetras.getSelectedItem());
    }//GEN-LAST:event_jComboBoxLetrasActionPerformed

    private void jButtonRecorreJLISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecorreJLISTActionPerformed
        int seleccion[]= jListSeleccion.getSelectedIndices();
        if (seleccion.length > 1) {
            System.out.println("Elementos seleccionados: ");
            for (int i = 0; i < seleccion.length; i++) {
                String num = (String) jListSeleccion.getModel().getElementAt(seleccion[i]);
                System.out.println("Seleccion; " + num);
            }
        } else if (seleccion.length == 1) {
            System.out.println("Elementos seleccionados: ");
            String num = (String) jListSeleccion.getModel().getElementAt(jListSeleccion.getSelectedIndex());
        } else {
            System.out.println("Ningun elemento seleccionado");
        }
        
    }//GEN-LAST:event_jButtonRecorreJLISTActionPerformed

    private void jListSeleccionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListSeleccionMousePressed
         String num = (String) jListSeleccion.getModel().getElementAt(jListSeleccion.getSelectedIndex());
         System.out.println("Num: " + num);
    }//GEN-LAST:event_jListSeleccionMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameComboSencillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameComboSencillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameComboSencillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameComboSencillo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameComboSencillo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRecorreJLIST;
    private javax.swing.JComboBox<String> jComboBoxLetras;
    private javax.swing.JLabel jLabelSelecciona;
    private javax.swing.JList<String> jListSeleccion;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
