/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ej15Listeners;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

/**
 *
 * @author DAM2Alu10
 */
public class JFrameListeners extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListeners
     */
    ActionListener a = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            System.out.println("No copies");
        }
    };

    public JFrameListeners() {
        initComponents();
        KeyStroke ctrl_C = KeyStroke.getKeyStroke(KeyEvent.VK_C, java.awt.Event.CTRL_MASK, true);
        getRootPane().registerKeyboardAction(a, ctrl_C, JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCopia = new javax.swing.JTextField();
        jLabelMensaje = new javax.swing.JLabel();
        jLabelMensajeCopia = new javax.swing.JLabel();
        jTextFieldOriginal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaArrastrar = new javax.swing.JTextArea();
        jButtonArrastrar = new javax.swing.JButton();
        jPanelContenedor = new javax.swing.JPanel();
        jPanelOculto = new javax.swing.JPanel();
        jLabelOculto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTextFieldCopia.setEditable(false);

        jLabelMensaje.setText("Mensaje");

        jLabelMensajeCopia.setText("Copia Mensaje");

        jTextFieldOriginal.setDragEnabled(true);
        jTextFieldOriginal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldOriginalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldOriginalFocusLost(evt);
            }
        });
        jTextFieldOriginal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOriginalActionPerformed(evt);
            }
        });
        jTextFieldOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldOriginalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldOriginalKeyReleased(evt);
            }
        });

        jTextAreaArrastrar.setColumns(20);
        jTextAreaArrastrar.setRows(5);
        jScrollPane1.setViewportView(jTextAreaArrastrar);

        jButtonArrastrar.setText("Arrastrar");
        jButtonArrastrar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jButtonArrastrarMouseDragged(evt);
            }
        });

        jPanelContenedor.setBackground(new java.awt.Color(255, 0, 0));
        jPanelContenedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelContenedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelContenedorMouseExited(evt);
            }
        });

        jLabelOculto.setText("Oculto");

        javax.swing.GroupLayout jPanelOcultoLayout = new javax.swing.GroupLayout(jPanelOculto);
        jPanelOculto.setLayout(jPanelOcultoLayout);
        jPanelOcultoLayout.setHorizontalGroup(
            jPanelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcultoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabelOculto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelOcultoLayout.setVerticalGroup(
            jPanelOcultoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOcultoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelOculto)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOculto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelOculto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonArrastrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 454, Short.MAX_VALUE)
                                .addComponent(jTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelContenedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelMensajeCopia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldCopia, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMensaje)
                    .addComponent(jTextFieldOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCopia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMensajeCopia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonArrastrar)
                .addGap(18, 18, 18)
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jPanelOculto.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void jTextFieldOriginalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOriginalActionPerformed
        System.out.println("Has apretado el Enter");
    }//GEN-LAST:event_jTextFieldOriginalActionPerformed

    private void jTextFieldOriginalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOriginalKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println("Capturada la tecla Enter");
        }
    }//GEN-LAST:event_jTextFieldOriginalKeyReleased

    private void jTextFieldOriginalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOriginalFocusGained
        System.out.println("Se ha ganado el foco");
    }//GEN-LAST:event_jTextFieldOriginalFocusGained

    private void jTextFieldOriginalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOriginalFocusLost
        System.out.println("Se ha perdido el foco");
        jTextAreaArrastrar.requestFocus();
    }//GEN-LAST:event_jTextFieldOriginalFocusLost

    private void jTextFieldOriginalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldOriginalKeyPressed
        jTextFieldCopia.setText(jTextFieldOriginal.getText());
        System.out.println("Tamaño actual: " + jTextFieldOriginal.getText().length());
        Color original = jTextFieldOriginal.getBackground();
        if (jTextFieldOriginal.getText().length() < 25) {
            jTextFieldOriginal.setBackground(original);
        } else if (jTextFieldOriginal.getText().length() > 30) {
            jTextFieldOriginal.setBackground(Color.red);
        } else {
            jTextFieldOriginal.setBackground(Color.yellow);
        }
    }//GEN-LAST:event_jTextFieldOriginalKeyPressed


    private void jButtonArrastrarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonArrastrarMouseDragged
        System.out.println("Arrastrando a la posicion: " + evt.getPoint());
    }//GEN-LAST:event_jButtonArrastrarMouseDragged

    private void jPanelContenedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelContenedorMouseEntered
        jPanelOculto.setVisible(true);
    }//GEN-LAST:event_jPanelContenedorMouseEntered

    private void jPanelContenedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelContenedorMouseExited
        jPanelOculto.setVisible(false);
    }//GEN-LAST:event_jPanelContenedorMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListeners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListeners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListeners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListeners.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListeners().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonArrastrar;
    private javax.swing.JLabel jLabelMensaje;
    private javax.swing.JLabel jLabelMensajeCopia;
    private javax.swing.JLabel jLabelOculto;
    private javax.swing.JPanel jPanelContenedor;
    private javax.swing.JPanel jPanelOculto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaArrastrar;
    private javax.swing.JTextField jTextFieldCopia;
    private javax.swing.JTextField jTextFieldOriginal;
    // End of variables declaration//GEN-END:variables
}
